### ISSUE TITLE
msColumnCorrection, msReadFrame broken

### ISSUE THREAD

**Issue by DenisPolygalov** [daharoni/Miniscope_Analysis#3]
msRun.m line: ms = msColumnCorrection(ms,5); %Generally not used 
First of all "Generally not used" is misleading because de-facto many following function calls use result generated by msColumnCorrection(). 
msColumnCorrection.m is broken or not compatible with Matlab R2011b I'm using. 
meanFrame = zeros(vidObj.height,vidObj.width); %allocate memory
The line above allocate 2D array (height x width), however,
msReadFrame(vidObj,frameNum,false,false,false) return 3D array (height x width x 3) causing this line to fail:
meanFrame = meanFrame + double(msReadFrame(vidObj,frameNum,false,false,false));

**Comment by daharoni** [comment]
You are right that msColumnCorrection still needs to be run. I'll update msRun with a proper description.

The issue you are having with msReadFrame is due to one of two things:
1) you are trying to read in a color video file. If this is the case you need to modify msReadFrame to handle RGB frames or reduce the RGB frame down to gray scale.
2) R2011b implements frame extraction from .avi files differently than R2013b. I know newer versions, R2016, of MATLAB switched how their VideoReader functions as well.

**Comment by DenisPolygalov** [comment]
Better way to avoid using of msColumnCorrection function in the msRun.m:
ms = msGenerateVideoObj(pwd,'msCam');
% ms = msColumnCorrection(ms,5); % <- comment or remove
ms.columnCorrection = zeros(ms.height, ms.width);
ms.columnCorrectionOffset = 0;
ms = msFluorFrameProps ... and so on.
